export const SET_CLASSIFY = 'SET_CLASSIFY'

export const SET_GOOD = 'SET_GOOD'

export const SET_TIME = 'SET_TIME'

export const SET_PICKITEMS = 'SET_PICKITEMS'

export const SET_BUYNUM = 'SET_BUYNUM'

export const TOGGLE_PENDINGLIST = 'TOGGLE_PENDINGLIST'

export const CLEAR_PENDINGLIST = 'CLEAR_PENDINGLIST'

export const SELECT_ALL_PENDINGLIST = 'SELECT_ALL_PENDINGLIST'

export const ADD_TO_CART = 'ADD_TO_CART'

export const CHANGE_NUM_CART = 'CHANGE_NUM_CART'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'

export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'

export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const TOGGLE_CHECKBOXMODEL = 'TOGGLE_CHECKBOXMODEL'

export const SET_CHECKBOXMODEL = 'SET_CHECKBOXMODEL'

export const SET_CHECKED = 'SET_CHECKED'
